export const types = {
	FILL_POSTS: 'FILL_POSTS',
	CREATE_POST: 'CREATE_POST',
	CLEAR_POSTS: 'CLEAR_POSTS',
	REMOVE_POST: 'REMOVE_POST',

	FETCH_POSTS_ASYNC: 'FETCH_POSTS_ASYNC',
	CREATE_POSTS_ASYNC: 'CREATE_POSTS_ASYNC',
	REMOVE_POST_ASYNC: 'REMOVE_POST_ASYNC',
}