export const types = {
	AUTHENTIFICATE: 'AUTHENTIFICATE',
	INITIALIZE: 'INITIALIZE',
	LOGOUT: 'LOGOUT',
	
	SIGNUP_ASYNC: 'SIGNUP_ASYNC',
	LOGIN_ASYNC: 'LOGIN_ASYNC',
	AUTHENTIFICATE_ASYNC: 'AUTHENTIFICATE_ASYNC',
	INITIALIZE_ASYNC: 'INITIALIZE_ASYNC',
	LOGOUT_ASYNC: 'LOGOUT_ASYNC',
}